"""Pradine migracija

Revision ID: 9d3cac76d536
Revises: 
Create Date: 2022-08-31 14:22:11.473556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d3cac76d536'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kategorijos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Pavadinimas', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kategorijos'))
    )
    op.create_table('vartotojas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Vardas', sa.String(length=20), nullable=False),
    sa.Column('El. pašto adresas', sa.String(length=120), nullable=False),
    sa.Column('Slaptažodis', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vartotojas')),
    sa.UniqueConstraint('El. pašto adresas', name=op.f('uq_vartotojas_El. pašto adresas')),
    sa.UniqueConstraint('Slaptažodis', name=op.f('uq_vartotojas_Slaptažodis')),
    sa.UniqueConstraint('Vardas', name=op.f('uq_vartotojas_Vardas'))
    )
    op.create_table('straipsniai',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Pavadinimas', sa.String(length=200), nullable=False),
    sa.Column('kategorija_id', sa.Integer(), nullable=True),
    sa.Column('vartotojas_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kategorija_id'], ['kategorijos.id'], name=op.f('fk_straipsniai_kategorija_id_kategorijos')),
    sa.ForeignKeyConstraint(['vartotojas_id'], ['vartotojas.id'], name=op.f('fk_straipsniai_vartotojas_id_vartotojas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_straipsniai'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('straipsniai')
    op.drop_table('vartotojas')
    op.drop_table('kategorijos')
    # ### end Alembic commands ###
